-- pgque--0.2.0--0.2.1.sql -- pg_tle update body.
-- Auto-generated by build/transform.sh. Do not edit or execute directly.
-- Copyright 2026 Nikolay Samokhvalov. Apache-2.0 license.
-- Includes code derived from PgQ (ISC license, Marko Kreen / Skype Technologies OU).

create or replace function pgque.receive(
    i_queue text, i_consumer text, i_max_return int default 100)
returns setof pgque.message as $$
declare
    v_batch_id bigint;
    ev record;
    cnt int := 0;
begin
    if i_max_return < 1 then
        raise exception 'pgque.receive: max_return must be >= 1, got %', i_max_return;
    end if;

    -- Get next batch (may return NULL if no tick window is ready)
    v_batch_id := pgque.next_batch(i_queue, i_consumer);
    if v_batch_id is null then
        return;
    end if;

    -- Yield messages from the batch
    for ev in
        select ev_id, ev_type, ev_data, ev_retry, ev_time,
               ev_extra1, ev_extra2, ev_extra3, ev_extra4
        from pgque.get_batch_events(v_batch_id)
    loop
        if cnt = i_max_return then
            raise exception 'pgque.receive: batch exceeds max_return of %', i_max_return
                using
                    errcode = '54000',
                    hint = 'Retry with a larger resource-safe max_return to receive the complete batch. Do not acknowledge after this error.';
        end if;
        return next row(
            ev.ev_id, v_batch_id, ev.ev_type, ev.ev_data,
            ev.ev_retry, ev.ev_time,
            ev.ev_extra1, ev.ev_extra2, ev.ev_extra3, ev.ev_extra4
        )::pgque.message;
        cnt := cnt + 1;
    end loop;

    -- Empty batch: finish immediately to advance the consumer cursor.
    if cnt = 0 then
        perform pgque.finish_batch(v_batch_id);
    end if;

    return;
end;
$$ language plpgsql security definer set search_path = pgque, pg_catalog;

create or replace function pgque.receive_coop(
    i_queue text,
    i_consumer text,
    i_subconsumer text,
    i_max_return int default 100,
    i_dead_interval interval default null)
returns setof pgque.message as $$
declare
    v_batch_id bigint;
    ev record;
    cnt int := 0;
begin
    if i_max_return < 1 then
        raise exception 'pgque.receive_coop: max_return must be >= 1, got %', i_max_return;
    end if;

    v_batch_id := pgque.next_batch(i_queue, i_consumer, i_subconsumer, i_dead_interval);
    if v_batch_id is null then
        return;
    end if;

    for ev in
        select
            ev_id,
            ev_type,
            ev_data,
            ev_retry,
            ev_time,
            ev_extra1,
            ev_extra2,
            ev_extra3,
            ev_extra4
        from pgque.get_batch_events(v_batch_id)
    loop
        if cnt = i_max_return then
            raise exception 'pgque.receive_coop: batch exceeds max_return of %', i_max_return
                using
                    errcode = '54000',
                    hint = 'Retry with a larger resource-safe max_return to receive the complete batch. Do not acknowledge after this error.';
        end if;
        return next row(
            ev.ev_id,
            v_batch_id,
            ev.ev_type,
            ev.ev_data,
            ev.ev_retry,
            ev.ev_time,
            ev.ev_extra1,
            ev.ev_extra2,
            ev.ev_extra3,
            ev.ev_extra4
        )::pgque.message;
        cnt := cnt + 1;
    end loop;

    -- Empty batch: release the member token so the subconsumer is not wedged
    -- on a tick window with no visible events. finish_batch on a coop_member
    -- clears sub_batch + sub_last_tick + sub_next_tick (it does not advance
    -- the main cursor, which already moved when the batch was allocated).
    if cnt = 0 then
        perform pgque.finish_batch(v_batch_id);
    end if;

    return;
end;
$$ language plpgsql security definer set search_path = pgque, pg_catalog;

create or replace function pgque.version()
returns text as $$
begin
    return '0.2.1';
end;
$$ language plpgsql security definer set search_path = pgque, pg_catalog;
