-- pgque--0.2.1--0.2.2.sql -- pg_tle update body.
-- Auto-generated by build/transform.sh. Do not edit or execute directly.
-- Copyright 2026 Nikolay Samokhvalov. Apache-2.0 license.
-- Includes code derived from PgQ (ISC license, Marko Kreen / Skype Technologies OU).

create or replace function pgque.version()
returns text as $$
begin
    return '0.2.2';
end;
$$ language plpgsql security definer set search_path = pgque, pg_catalog;
